---
    - name: ensure python-software-properties is installed
      apt: pkg=python-software-properties state=installed

    - name: add rabbitmq official apt repository
      apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

    - name: add trusted key
      apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

    - name: update keys
      command: "apt-key update && apt-get update"

    - name: install package
      apt: name={{ item }} allow_unauthenticated=yes update_cache=yes state=installed
      with_items:
        - rabbitmq-server

    - name: enable rabbitmq plugins
      rabbitmq_plugin: names=rabbitmq_management